services:
  mongodb:
    image: mongo:7-jammy
    ports:
    - '27017:27017'
    volumes:
    - dbdata:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: java -DServer.port=$PORT -jar /app/target/digimon-tcg-sim.jar
    depends_on:
    - mongodb
    environment:
    - ENVIRONMENT=dev
    - PORT=8080
    ports:
    - '8080:8080'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run dev
    environment:      
    - BACKEND_URL=http://backend:8080
    - ENVIRONMENT=dev
    - NODE_ENV=development
    ports:
    - '5173:5173'
    volumes:
    - ./frontend/src:/app/src:cached
    - ./frontend/public:/app/public:cached
    - ./frontend/index.html:/app/index.html:cached

volumes:
  dbdata: