name: "Deploy App"

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn -B package --file backend/pom.xml

      - name: Build Docker Image
        run: docker build -t my-docker-image .

      - name: Push Docker Image to Registry
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker tag my-docker-image ${{ secrets.DOCKERHUB_USERNAME }}/my-docker-image:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-docker-image:latest

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: your-heroku-app-name
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          buildpacks: 'heroku/java'
          used_yml: true
          env_vars: MONGO_DB_URI=${{ secrets.MONGO_DB_URI }}

      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://digimon-tcg.herokuapp.com
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
