name: Deploy to Heroku
on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/dist/

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'temurin'
      - uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: backend/src/main/resources/static
      - name: Build Backend
        run: mvn -B package --file backend/pom.xml
      - uses: actions/upload-artifact@v3
        with:
          name: backend-build
          path: backend/target/digimon-tcg-sim.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build-backend
    environment:
      name: production-heroku
      url: https://digimon-tcg.herokuapp.com/
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: backend-build
          path: backend/target
      - name: Login to Heroku
        run: heroku container:login
      - name: Push Docker Container
        run: heroku container:push web -a digimon-tcg  --context backend
      - name: Release Docker Container
        run: heroku container:release web -a digimon-tcg
